SKELETONS = rss.bpf.skeleton.h bpf_fault_snapshot.bpf.skeleton.h

LLVM_STRIP ?= llvm-strip
CLANG ?= clang
INC_FLAGS = `$(CLANG) -print-file-name=include`
EXTRA_CFLAGS ?= -O2 -g -target bpf

all: $(SKELETONS)

.PHONY: clean

clean:
	rm -f $(SKELETONS) $(SKELETONS:%.skeleton.h=%.o)

vmlinux.h:
	bpftool btf dump file /sys/kernel/btf/vmlinux format c > $@

%.o: %.c
	$(CLANG) $(INC_FLAGS) \
                -D__KERNEL__ -D__ASM_SYSREG_H \
                -I../include $(LINUXINCLUDE) \
                $(EXTRA_CFLAGS) -c $< -o $@
	$(LLVM_STRIP) -g $@

rss.bpf.skeleton.h: rss.bpf.o
	bpftool gen skeleton $< > $@
	cp $@ ../../ebpf/

bpf_fault_snapshot.bpf.o: bpf_fault_snapshot.bpf.c vmlinux.h
	$(CLANG) $(INC_FLAGS) \
                -D__KERNEL__ -D__ASM_SYSREG_H \
                -I. $(LINUXINCLUDE) \
                $(EXTRA_CFLAGS) -c $< -o $@
	$(LLVM_STRIP) -g $@

bpf_fault_snapshot.bpf.skeleton.h: bpf_fault_snapshot.bpf.o
	bpftool gen skeleton $< > $@
	cp $@ ../../migration/
